In [210]:
import pandas as pd

In [211]:
df=pd.read_csv("Attrition_dataset.csv")
df

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
0,1318,12/31/2006 0:00,1/3/1954,8/28/1989,1/1/1900,52,17,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2006,ACTIVE,HEADOFFICE
1,1318,12/31/2007 0:00,1/3/1954,8/28/1989,1/1/1900,53,18,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2007,ACTIVE,HEADOFFICE
2,1318,12/31/2008 0:00,1/3/1954,8/28/1989,1/1/1900,54,19,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2008,ACTIVE,HEADOFFICE
3,1318,12/31/2009 0:00,1/3/1954,8/28/1989,1/1/1900,55,20,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2009,ACTIVE,HEADOFFICE
4,1318,12/31/2010 0:00,1/3/1954,8/28/1989,1/1/1900,56,21,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2010,ACTIVE,HEADOFFICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49648,8258,12/1/2015 0:00,5/28/1994,8/19/2013,12/30/2015,21,2,Valemount,Dairy,Dairy Person,34,M,Male,Layoff,Involuntary,2015,TERMINATED,STORES
49649,8264,8/1/2013 0:00,6/13/1994,8/27/2013,8/30/2013,19,0,Vancouver,Customer Service,Cashier,44,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49650,8279,12/1/2015 0:00,7/18/1994,9/15/2013,12/30/2015,21,2,White Rock,Customer Service,Cashier,39,F,Female,Layoff,Involuntary,2015,TERMINATED,STORES
49651,8296,12/1/2013 0:00,9/2/1994,10/9/2013,12/31/2013,19,0,Kelowna,Customer Service,Cashier,16,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49652,8321,12/1/2014 0:00,11/28/1994,11/24/2013,12/30/2014,20,1,Grand Forks,Customer Service,Cashier,13,F,Female,Layoff,Involuntary,2014,TERMINATED,STORES

In [212]:
df.head()

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
0,1318,12/31/2006 0:00,1/3/1954,8/28/1989,1/1/1900,52,17,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2006,ACTIVE,HEADOFFICE
1,1318,12/31/2007 0:00,1/3/1954,8/28/1989,1/1/1900,53,18,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2007,ACTIVE,HEADOFFICE
2,1318,12/31/2008 0:00,1/3/1954,8/28/1989,1/1/1900,54,19,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2008,ACTIVE,HEADOFFICE
3,1318,12/31/2009 0:00,1/3/1954,8/28/1989,1/1/1900,55,20,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2009,ACTIVE,HEADOFFICE
4,1318,12/31/2010 0:00,1/3/1954,8/28/1989,1/1/1900,56,21,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2010,ACTIVE,HEADOFFICE

In [213]:
df.tail()

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
49648,8258,12/1/2015 0:00,5/28/1994,8/19/2013,12/30/2015,21,2,Valemount,Dairy,Dairy Person,34,M,Male,Layoff,Involuntary,2015,TERMINATED,STORES
49649,8264,8/1/2013 0:00,6/13/1994,8/27/2013,8/30/2013,19,0,Vancouver,Customer Service,Cashier,44,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49650,8279,12/1/2015 0:00,7/18/1994,9/15/2013,12/30/2015,21,2,White Rock,Customer Service,Cashier,39,F,Female,Layoff,Involuntary,2015,TERMINATED,STORES
49651,8296,12/1/2013 0:00,9/2/1994,10/9/2013,12/31/2013,19,0,Kelowna,Customer Service,Cashier,16,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
49652,8321,12/1/2014 0:00,11/28/1994,11/24/2013,12/30/2014,20,1,Grand Forks,Customer Service,Cashier,13,F,Female,Layoff,Involuntary,2014,TERMINATED,STORES

In [214]:
# to find the no of records and columns in a DataFrame
df.shape

(49653, 18)

In [215]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49653 entries, 0 to 49652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EmployeeID           49653 non-null  int64
 1   recorddate_key       49653 non-null  object
 2   birthdate_key        49653 non-null  object
 3   orighiredate_key     49653 non-null  object
 4   terminationdate_key  49653 non-null  object
 5   age                  49653 non-null  int64
 6   length_of_service    49653 non-null  int64
 7   city_name            49653 non-null  object
 8   department_name      49653 non-null  object
 9   job_title            49653 non-null  object
 10  store_name           49653 non-null  int64
 11  gender_short         49653 non-null  object
 12  gender_full          49653 non-null  object
 13  termreason_desc      49653 non-null  object
 14  termtype_desc        49653 non-null  object
 15  STATUS_YEAR          49653 non-null  int64
 16  STATUS               49653 non-null  object
 17  BUSINESS_UNIT        49653 non-null  object
dtypes: int64(5), object(13)
memory usage: 6.8+ MB




Before cleaning we have to extract
info is used to check for nul values

## **CLEANING**

-> Cheking for null values

-> Checking duplicates --------duplicated() -> False ------> no duplicated records( it checks rows)

                               duplicated(subset='')---> True-->duplicate records

In [216]:
df.duplicated(subset='EmployeeID').any()

# df=df.duplicated(subset='EmployeeID')

True

# Drop the Duplicates

In [217]:
# df.drop_duplicates(subset='EmployeeID')

#to keep latest updated records
df=df.drop_duplicates(subset='EmployeeID',keep='last')

In [218]:
df.shape

(6284, 18)

In [219]:
# Convert the object datatype into date format
col=['recorddate_key','birthdate_key','orighiredate_key','terminationdate_key']
for i in col:
    df[i]=pd.to_datetime(df[i])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_19412\2753947107.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]=pd.to_datetime(df[i])
C:\Users\ASUS\AppData\Local\Temp\ipykernel_19412\2753947107.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]=pd.to_datetime(df[i])
C:\Users\ASUS\AppData\Local\Temp\ipykernel_19412\2753947107.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]=pd.to_datetime(df[i])
C:\Users\ASUS\AppData\Local\Temp\ipykernel_19412\2753947107.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i]=pd.to_datetime(df[i])

In [220]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6284 entries, 9 to 49652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   EmployeeID           6284 non-null   int64
 1   recorddate_key       6284 non-null   datetime64[ns]
 2   birthdate_key        6284 non-null   datetime64[ns]
 3   orighiredate_key     6284 non-null   datetime64[ns]
 4   terminationdate_key  6284 non-null   datetime64[ns]
 5   age                  6284 non-null   int64
 6   length_of_service    6284 non-null   int64
 7   city_name            6284 non-null   object
 8   department_name      6284 non-null   object
 9   job_title            6284 non-null   object
 10  store_name           6284 non-null   int64
 11  gender_short         6284 non-null   object
 12  gender_full          6284 non-null   object
 13  termreason_desc      6284 non-null   object
 14  termtype_desc        6284 non-null   object
 15  STATUS_YEAR          6284 non-null   int64
 16  STATUS               6284 non-null   object
 17  BUSINESS_UNIT        6284 non-null   object
dtypes: datetime64[ns](4), int64(5), object(9)
memory usage: 932.8+ KB

In [221]:
df=df.reset_index(drop=True)

In [222]:
df=df.drop(columns=['store_name','gender_short'])

## Rename the columns

In [223]:
# df.columns()


col_list=['EMP_ID','Record_date','DOB','Hiredate','Term_Date','Age','Experience','City','Dname','JOB','Gender','Term_reason','term Type','Year','Status', 'Business_unit']
df.columns=col_list
df

,EMP_ID,Record_date,DOB,Hiredate,Term_Date,Age,Experience,City,Dname,JOB,Gender,Term_reason,term Type,Year,Status,Business_unit
0,1318,2015-12-31,1954-01-03,1989-08-28,1900-01-01,61,26,Vancouver,Executive,CEO,Male,Not Applicable,Not Applicable,2015,ACTIVE,HEADOFFICE
1,1319,2015-12-31,1957-01-03,1989-08-28,1900-01-01,58,26,Vancouver,Executive,VP Stores,Female,Not Applicable,Not Applicable,2015,ACTIVE,HEADOFFICE
2,1320,2015-12-31,1955-01-02,1989-08-28,1900-01-01,60,26,Vancouver,Executive,Legal Counsel,Female,Not Applicable,Not Applicable,2015,ACTIVE,HEADOFFICE
3,1321,2015-12-31,1959-01-02,1989-08-28,1900-01-01,56,26,Vancouver,Executive,VP Human Resources,Male,Not Applicable,Not Applicable,2015,ACTIVE,HEADOFFICE
4,1322,2015-12-31,1958-01-09,1989-08-31,1900-01-01,57,26,Vancouver,Executive,VP Finance,Male,Not Applicable,Not Applicable,2015,ACTIVE,HEADOFFICE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6279,8258,2015-12-01,1994-05-28,2013-08-19,2015-12-30,21,2,Valemount,Dairy,Dairy Person,Male,Layoff,Involuntary,2015,TERMINATED,STORES
6280,8264,2013-08-01,1994-06-13,2013-08-27,2013-08-30,19,0,Vancouver,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
6281,8279,2015-12-01,1994-07-18,2013-09-15,2015-12-30,21,2,White Rock,Customer Service,Cashier,Female,Layoff,Involuntary,2015,TERMINATED,STORES
6282,8296,2013-12-01,1994-09-02,2013-10-09,2013-12-31,19,0,Kelowna,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,TERMINATED,STORES
6283,8321,2014-12-01,1994-11-28,2013-11-24,2014-12-30,20,1,Grand Forks,Customer Service,Cashier,Female,Layoff,Involuntary,2014,TERMINATED,STORES

In [224]:
df['Status']=df['Status'].str.title()
df['Business_unit']=df['Business_unit'].str.title()

In [225]:
df

,EMP_ID,Record_date,DOB,Hiredate,Term_Date,Age,Experience,City,Dname,JOB,Gender,Term_reason,term Type,Year,Status,Business_unit
0,1318,2015-12-31,1954-01-03,1989-08-28,1900-01-01,61,26,Vancouver,Executive,CEO,Male,Not Applicable,Not Applicable,2015,Active,Headoffice
1,1319,2015-12-31,1957-01-03,1989-08-28,1900-01-01,58,26,Vancouver,Executive,VP Stores,Female,Not Applicable,Not Applicable,2015,Active,Headoffice
2,1320,2015-12-31,1955-01-02,1989-08-28,1900-01-01,60,26,Vancouver,Executive,Legal Counsel,Female,Not Applicable,Not Applicable,2015,Active,Headoffice
3,1321,2015-12-31,1959-01-02,1989-08-28,1900-01-01,56,26,Vancouver,Executive,VP Human Resources,Male,Not Applicable,Not Applicable,2015,Active,Headoffice
4,1322,2015-12-31,1958-01-09,1989-08-31,1900-01-01,57,26,Vancouver,Executive,VP Finance,Male,Not Applicable,Not Applicable,2015,Active,Headoffice
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6279,8258,2015-12-01,1994-05-28,2013-08-19,2015-12-30,21,2,Valemount,Dairy,Dairy Person,Male,Layoff,Involuntary,2015,Terminated,Stores
6280,8264,2013-08-01,1994-06-13,2013-08-27,2013-08-30,19,0,Vancouver,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores
6281,8279,2015-12-01,1994-07-18,2013-09-15,2015-12-30,21,2,White Rock,Customer Service,Cashier,Female,Layoff,Involuntary,2015,Terminated,Stores
6282,8296,2013-12-01,1994-09-02,2013-10-09,2013-12-31,19,0,Kelowna,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores
6283,8321,2014-12-01,1994-11-28,2013-11-24,2014-12-30,20,1,Grand Forks,Customer Service,Cashier,Female,Layoff,Involuntary,2014,Terminated,Stores

In [226]:
## to create the age category
# check for starting age

# use the min and max
df[['Age','Experience']].agg(['min','max'])

     Age  Experience
min   19           0
max   65          26

In [227]:
# age columns are numerical column, with continuous range use-----------> cut function
# 18-25 range , 18 excluded, 25 included, 

df['Age_category']=pd.cut(df['Age'], bins=[18,25,59,65],labels=['Teen','Adult','Senior'])
df

,EMP_ID,Record_date,DOB,Hiredate,Term_Date,Age,Experience,City,Dname,JOB,Gender,Term_reason,term Type,Year,Status,Business_unit,Age_category
0,1318,2015-12-31,1954-01-03,1989-08-28,1900-01-01,61,26,Vancouver,Executive,CEO,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior
1,1319,2015-12-31,1957-01-03,1989-08-28,1900-01-01,58,26,Vancouver,Executive,VP Stores,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult
2,1320,2015-12-31,1955-01-02,1989-08-28,1900-01-01,60,26,Vancouver,Executive,Legal Counsel,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior
3,1321,2015-12-31,1959-01-02,1989-08-28,1900-01-01,56,26,Vancouver,Executive,VP Human Resources,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult
4,1322,2015-12-31,1958-01-09,1989-08-31,1900-01-01,57,26,Vancouver,Executive,VP Finance,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6279,8258,2015-12-01,1994-05-28,2013-08-19,2015-12-30,21,2,Valemount,Dairy,Dairy Person,Male,Layoff,Involuntary,2015,Terminated,Stores,Teen
6280,8264,2013-08-01,1994-06-13,2013-08-27,2013-08-30,19,0,Vancouver,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores,Teen
6281,8279,2015-12-01,1994-07-18,2013-09-15,2015-12-30,21,2,White Rock,Customer Service,Cashier,Female,Layoff,Involuntary,2015,Terminated,Stores,Teen
6282,8296,2013-12-01,1994-09-02,2013-10-09,2013-12-31,19,0,Kelowna,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores,Teen
6283,8321,2014-12-01,1994-11-28,2013-11-24,2014-12-30,20,1,Grand Forks,Customer Service,Cashier,Female,Layoff,Involuntary,2014,Terminated,Stores,Teen

Creating new column service category based on experience

In [228]:
df['Service Category']=pd.cut(df['Experience'],bins=[-1,1,5,26],labels=['Freshers','Senior','Experts'])
df

,EMP_ID,Record_date,DOB,Hiredate,Term_Date,Age,Experience,City,Dname,JOB,Gender,Term_reason,term Type,Year,Status,Business_unit,Age_category,Service Category
0,1318,2015-12-31,1954-01-03,1989-08-28,1900-01-01,61,26,Vancouver,Executive,CEO,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior,Experts
1,1319,2015-12-31,1957-01-03,1989-08-28,1900-01-01,58,26,Vancouver,Executive,VP Stores,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
2,1320,2015-12-31,1955-01-02,1989-08-28,1900-01-01,60,26,Vancouver,Executive,Legal Counsel,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior,Experts
3,1321,2015-12-31,1959-01-02,1989-08-28,1900-01-01,56,26,Vancouver,Executive,VP Human Resources,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
4,1322,2015-12-31,1958-01-09,1989-08-31,1900-01-01,57,26,Vancouver,Executive,VP Finance,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6279,8258,2015-12-01,1994-05-28,2013-08-19,2015-12-30,21,2,Valemount,Dairy,Dairy Person,Male,Layoff,Involuntary,2015,Terminated,Stores,Teen,Senior
6280,8264,2013-08-01,1994-06-13,2013-08-27,2013-08-30,19,0,Vancouver,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores,Teen,Freshers
6281,8279,2015-12-01,1994-07-18,2013-09-15,2015-12-30,21,2,White Rock,Customer Service,Cashier,Female,Layoff,Involuntary,2015,Terminated,Stores,Teen,Senior
6282,8296,2013-12-01,1994-09-02,2013-10-09,2013-12-31,19,0,Kelowna,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores,Teen,Freshers
6283,8321,2014-12-01,1994-11-28,2013-11-24,2014-12-30,20,1,Grand Forks,Customer Service,Cashier,Female,Layoff,Involuntary,2014,Terminated,Stores,Teen,Freshers

In [229]:
df['Dname'].unique()

array(['Executive', 'Store Management', 'Meats', 'Recruitment',
       'Customer Service', 'Produce', 'Bakery', 'Dairy',
       'Processed Foods', 'Training', 'Labor Relations', 'HR Technology',
       'Employee Records', 'Compensation', 'Legal',
       'Accounts Receiveable', 'Information Technology',
       'Accounts Payable', 'Audit', 'Accounting', 'Investment'],
      dtype=object)

In [230]:
df['JOB'].unique()

array(['CEO', 'VP Stores', 'Legal Counsel', 'VP Human Resources',
       'VP Finance', 'Exec Assistant, VP Stores',
       'Exec Assistant, Legal Counsel', 'CHief Information Officer',
       'Store Manager', 'Meats Manager',
       'Exec Assistant, Human Resources', 'Exec Assistant, Finance',
       'Director, Recruitment', 'Meat Cutter', 'Customer Service Manager',
       'Produce Manager', 'Bakery Manager', 'Dairy Person',
       'Processed Foods Manager', 'Produce Clerk', 'Baker',
       'Shelf Stocker', 'Cashier', 'Director, Training',
       'Director, Labor Relations', 'Director, HR Technology',
       'Director, Employee Records', 'Director, Compensation',
       'Corporate Lawyer', 'Director, Accounts Receivable',
       'Systems Analyst', 'Director, Accounts Payable', 'Director, Audit',
       'Director, Accounting', 'Director, Investments', 'Recruiter',
       'Trainer', 'Labor Relations Analyst', 'Dairy Manager',
       'HRIS Analyst', 'Benefits Admin', 'Compensation Analyst',
       'Accounts Receiveable Clerk', 'Accounts Payable Clerk', 'Auditor',
       'Accounting Clerk', 'Investment Analyst'], dtype=object)

## apply

In [231]:
def job_clean(row):
    j=row['JOB']
    d=row['Dname']
    if j!='Auditor' and j!='Dairy Person':
        if d in j:
            return j.replace(d,'').strip(',').strip(',s')
        else:
            return j.removeprefix('Exec Assistant').strip(',v')
        

## strip is used to remove the end values

In [232]:
df['JOB']=df.apply(job_clean,axis=1)


df

,EMP_ID,Record_date,DOB,Hiredate,Term_Date,Age,Experience,City,Dname,JOB,Gender,Term_reason,term Type,Year,Status,Business_unit,Age_category,Service Category
0,1318,2015-12-31,1954-01-03,1989-08-28,1900-01-01,61,26,Vancouver,Executive,CEO,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior,Experts
1,1319,2015-12-31,1957-01-03,1989-08-28,1900-01-01,58,26,Vancouver,Executive,VP Stores,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
2,1320,2015-12-31,1955-01-02,1989-08-28,1900-01-01,60,26,Vancouver,Executive,Legal Counsel,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior,Experts
3,1321,2015-12-31,1959-01-02,1989-08-28,1900-01-01,56,26,Vancouver,Executive,VP Human Resources,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
4,1322,2015-12-31,1958-01-09,1989-08-31,1900-01-01,57,26,Vancouver,Executive,VP Finance,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6279,8258,2015-12-01,1994-05-28,2013-08-19,2015-12-30,21,2,Valemount,Dairy,None,Male,Layoff,Involuntary,2015,Terminated,Stores,Teen,Senior
6280,8264,2013-08-01,1994-06-13,2013-08-27,2013-08-30,19,0,Vancouver,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores,Teen,Freshers
6281,8279,2015-12-01,1994-07-18,2013-09-15,2015-12-30,21,2,White Rock,Customer Service,Cashier,Female,Layoff,Involuntary,2015,Terminated,Stores,Teen,Senior
6282,8296,2013-12-01,1994-09-02,2013-10-09,2013-12-31,19,0,Kelowna,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores,Teen,Freshers
6283,8321,2014-12-01,1994-11-28,2013-11-24,2014-12-30,20,1,Grand Forks,Customer Service,Cashier,Female,Layoff,Involuntary,2014,Terminated,Stores,Teen,Freshers

In [233]:
df['JOB'].unique()

array(['CEO', 'VP Stores', 'Legal Counsel', 'VP Human Resources',
       'VP Finance', ' VP Stores', ' Legal Counsel',
       'CHief Information Officer', 'Store Manager', ' Manager',
       ' Human Resources', ' Finance', 'Director, ', 'Meat Cutter', None,
       ' Clerk', 'Baker', 'Shelf Stocker', 'Cashier', 'Corporate Lawyer',
       'Director, Accounts Receivable', 'Systems Analyst', 'Recruiter',
       'Trainer', ' Analyst', 'HRIS Analyst', 'Benefits Admin'],
      dtype=object)

In [234]:
df['JOB']=df['JOB'].replace('CHief Information Officer','Chief Information Officer')

In [235]:
df

,EMP_ID,Record_date,DOB,Hiredate,Term_Date,Age,Experience,City,Dname,JOB,Gender,Term_reason,term Type,Year,Status,Business_unit,Age_category,Service Category
0,1318,2015-12-31,1954-01-03,1989-08-28,1900-01-01,61,26,Vancouver,Executive,CEO,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior,Experts
1,1319,2015-12-31,1957-01-03,1989-08-28,1900-01-01,58,26,Vancouver,Executive,VP Stores,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
2,1320,2015-12-31,1955-01-02,1989-08-28,1900-01-01,60,26,Vancouver,Executive,Legal Counsel,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior,Experts
3,1321,2015-12-31,1959-01-02,1989-08-28,1900-01-01,56,26,Vancouver,Executive,VP Human Resources,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
4,1322,2015-12-31,1958-01-09,1989-08-31,1900-01-01,57,26,Vancouver,Executive,VP Finance,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6279,8258,2015-12-01,1994-05-28,2013-08-19,2015-12-30,21,2,Valemount,Dairy,None,Male,Layoff,Involuntary,2015,Terminated,Stores,Teen,Senior
6280,8264,2013-08-01,1994-06-13,2013-08-27,2013-08-30,19,0,Vancouver,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores,Teen,Freshers
6281,8279,2015-12-01,1994-07-18,2013-09-15,2015-12-30,21,2,White Rock,Customer Service,Cashier,Female,Layoff,Involuntary,2015,Terminated,Stores,Teen,Senior
6282,8296,2013-12-01,1994-09-02,2013-10-09,2013-12-31,19,0,Kelowna,Customer Service,Cashier,Female,Resignaton,Voluntary,2013,Terminated,Stores,Teen,Freshers
6283,8321,2014-12-01,1994-11-28,2013-11-24,2014-12-30,20,1,Grand Forks,Customer Service,Cashier,Female,Layoff,Involuntary,2014,Terminated,Stores,Teen,Freshers

## **Check how many peoples are active**

->>>> use **loc[]** method 

->> record on which date it has recored.........

In [236]:
df.loc[df['Status']=='Active','Record_date'].unique()

<DatetimeArray>
['2015-12-31 00:00:00']
Length: 1, dtype: datetime64[ns]

->> check weather the active members has termination date

->> unique is used

In [237]:
df.loc[df['Status']=='Active','Term_Date'].unique()

<DatetimeArray>
['1900-01-01 00:00:00']
Length: 1, dtype: datetime64[ns]

active people should nothave he termination date so replace Term_Date-->

In [238]:
df.loc[df['Status']=='Active','Term_Date']='2015-12-31'

In [239]:
df.loc[df['Status']=='Active']

,EMP_ID,Record_date,DOB,Hiredate,Term_Date,Age,Experience,City,Dname,JOB,Gender,Term_reason,term Type,Year,Status,Business_unit,Age_category,Service Category
0,1318,2015-12-31,1954-01-03,1989-08-28,2015-12-31,61,26,Vancouver,Executive,CEO,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior,Experts
1,1319,2015-12-31,1957-01-03,1989-08-28,2015-12-31,58,26,Vancouver,Executive,VP Stores,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
2,1320,2015-12-31,1955-01-02,1989-08-28,2015-12-31,60,26,Vancouver,Executive,Legal Counsel,Female,Not Applicable,Not Applicable,2015,Active,Headoffice,Senior,Experts
3,1321,2015-12-31,1959-01-02,1989-08-28,2015-12-31,56,26,Vancouver,Executive,VP Human Resources,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
4,1322,2015-12-31,1958-01-09,1989-08-31,2015-12-31,57,26,Vancouver,Executive,VP Finance,Male,Not Applicable,Not Applicable,2015,Active,Headoffice,Adult,Experts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4794,8332,2015-12-31,1994-12-20,2013-12-05,2015-12-31,21,2,Langley,Customer Service,Cashier,Female,Not Applicable,Not Applicable,2015,Active,Stores,Teen,Senior
4795,8333,2015-12-31,1994-12-19,2013-12-05,2015-12-31,21,2,Fort St John,Customer Service,Cashier,Male,Not Applicable,Not Applicable,2015,Active,Stores,Teen,Senior
4796,8334,2015-12-31,1994-12-27,2013-12-09,2015-12-31,21,2,West Vancouver,Customer Service,Cashier,Female,Not Applicable,Not Applicable,2015,Active,Stores,Teen,Senior
4797,8335,2015-12-31,1994-12-28,2013-12-10,2015-12-31,21,2,Vancouver,Dairy,None,Female,Not Applicable,Not Applicable,2015,Active,Stores,Teen,Senior
4798,8336,2015-12-31,1994-12-31,2013-12-11,2015-12-31,21,2,Vancouver,Dairy,None,Male,Not Applicable,Not Applicable,2015,Active,Stores,Teen,Senior

## **Display the count of employess hired in each year**

In [240]:
df['Hiredate']

0      1989-08-28
1      1989-08-28
2      1989-08-28
3      1989-08-28
4      1989-08-31
          ...
6279   2013-08-19
6280   2013-08-27
6281   2013-09-15
6282   2013-10-09
6283   2013-11-24
Name: Hiredate, Length: 6284, dtype: datetime64[ns]

reset_index -> to convert into table(DatafRame)

In [241]:
h_df=df['Hiredate'].dt.year.value_counts().sort_values().reset_index()
h_df

    Hiredate  count
0       1989     86
1       1991    200
2       2001    212
3       2004    214
4       1990    214
5       2013    218
6       2003    218
7       2007    237
8       2002    238
9       2006    239
10      2011    242
11      2008    246
12      1992    248
13      2009    249
14      2010    254
15      2005    256
16      2012    259
17      1996    273
18      1994    298
19      1993    298
20      2000    305
21      1997    312
22      1995    312
23      1999    315
24      1998    341

In [242]:
h_df.columns=['Year','No_of_hirings']
h_df

    Year  No_of_hirings
0   1989             86
1   1991            200
2   2001            212
3   2004            214
4   1990            214
5   2013            218
6   2003            218
7   2007            237
8   2002            238
9   2006            239
10  2011            242
11  2008            246
12  1992            248
13  2009            249
14  2010            254
15  2005            256
16  2012            259
17  1996            273
18  1994            298
19  1993            298
20  2000            305
21  1997            312
22  1995            312
23  1999            315
24  1998            341

## **Display the termination details**

filter the termination details

In [1]:
t_df=df.loc[df['Status']=='Terminated','Term_Date'].dt.year.value_counts().sort_values().reset_index()
t_df.columns=['Year','No_of_Terminations']
t_df

NameError: name 'df' is not defined

## Merge both the tables

on: based on which column we are merging

how:it is used for join contion( )

        Why Full Outer join?

        why not inner join?
             some of the year does not have termination, it will some some values

In [244]:
pd.merge(h_df,t_df,on='Year',how='outer')

    Year  No_of_hirings  No_of_Terminations
0   1989           86.0                 NaN
1   1990          214.0                 NaN
2   1991          200.0                 NaN
3   1992          248.0                 NaN
4   1993          298.0                 NaN
5   1994          298.0                 NaN
6   1995          312.0                 NaN
7   1996          273.0                 NaN
8   1997          312.0                 NaN
9   1998          341.0                 NaN
10  1999          315.0                 NaN
11  2000          305.0                 NaN
12  2001          212.0                 NaN
13  2002          238.0                 NaN
14  2003          218.0                 NaN
15  2004          214.0                 NaN
16  2005          256.0                 NaN
17  2006          239.0               134.0
18  2007          237.0               162.0
19  2008          246.0               164.0
20  2009          249.0               142.0
21  2010          254.0               123.0
22  2011          242.0               110.0
23  2012          259.0               130.0
24  2013          218.0               105.0
25  2014            NaN               253.0
26  2015            NaN               162.0

In [245]:
df1=pd.merge(h_df,t_df,on='Year',how='outer').fillna(0).astype(int)
df1

    Year  No_of_hirings  No_of_Terminations
0   1989             86                   0
1   1990            214                   0
2   1991            200                   0
3   1992            248                   0
4   1993            298                   0
5   1994            298                   0
6   1995            312                   0
7   1996            273                   0
8   1997            312                   0
9   1998            341                   0
10  1999            315                   0
11  2000            305                   0
12  2001            212                   0
13  2002            238                   0
14  2003            218                   0
15  2004            214                   0
16  2005            256                   0
17  2006            239                 134
18  2007            237                 162
19  2008            246                 164
20  2009            249                 142
21  2010            254                 123
22  2011            242                 110
23  2012            259                 130
24  2013            218                 105
25  2014              0                 253
26  2015              0                 162

In [246]:
df1['Retention1']=df1['No_of_hirings']-df1['No_of_Terminations']
df1

    Year  No_of_hirings  No_of_Terminations  Retention1
0   1989             86                   0          86
1   1990            214                   0         214
2   1991            200                   0         200
3   1992            248                   0         248
4   1993            298                   0         298
5   1994            298                   0         298
6   1995            312                   0         312
7   1996            273                   0         273
8   1997            312                   0         312
9   1998            341                   0         341
10  1999            315                   0         315
11  2000            305                   0         305
12  2001            212                   0         212
13  2002            238                   0         238
14  2003            218                   0         218
15  2004            214                   0         214
16  2005            256                   0         256
17  2006            239                 134         105
18  2007            237                 162          75
19  2008            246                 164          82
20  2009            249                 142         107
21  2010            254                 123         131
22  2011            242                 110         132
23  2012            259                 130         129
24  2013            218                 105         113
25  2014              0                 253        -253
26  2015              0                 162        -162

In [247]:
df1['Retention']=df1['Retention1'].cumsum()
df1=df1.drop(columns='Retention1')
df1

    Year  No_of_hirings  No_of_Terminations  Retention
0   1989             86                   0         86
1   1990            214                   0        300
2   1991            200                   0        500
3   1992            248                   0        748
4   1993            298                   0       1046
5   1994            298                   0       1344
6   1995            312                   0       1656
7   1996            273                   0       1929
8   1997            312                   0       2241
9   1998            341                   0       2582
10  1999            315                   0       2897
11  2000            305                   0       3202
12  2001            212                   0       3414
13  2002            238                   0       3652
14  2003            218                   0       3870
15  2004            214                   0       4084
16  2005            256                   0       4340
17  2006            239                 134       4445
18  2007            237                 162       4520
19  2008            246                 164       4602
20  2009            249                 142       4709
21  2010            254                 123       4840
22  2011            242                 110       4972
23  2012            259                 130       5101
24  2013            218                 105       5214
25  2014              0                 253       4961
26  2015              0                 162       4799

In [248]:
df.loc[df['Status']=='Active'].shape

(4799, 18)

## **Cumulative SUM**

Therefore,

it displays the no of employess hired in each year, and who are active

Hence the data is correct