# Series Creation

In [2]:
import pandas as pd 
l=['red','green','blue','green','violet']
s=pd.Series(l,name='colours')

In [3]:
s

0       red
1     green
2      blue
3     green
4    violet
Name: colours, dtype: object

In [4]:
print(10+20)
print(100+200)

30
300

In [5]:
10+20
1000+2000

3000

In [6]:
s[0]

'red'

In [7]:
# s[-1]  key error

In [8]:
s[1]='orange'  #to change the value   #assignment operator will be always permanent

In [9]:
s

0       red
1    orange
2      blue
3     green
4    violet
Name: colours, dtype: object

In [10]:
s.drop(index=4)  #remove the cell value  #it is not assignment value it is temporary

0       red
1    orange
2      blue
3     green
Name: colours, dtype: object

In [11]:
s

0       red
1    orange
2      blue
3     green
4    violet
Name: colours, dtype: object

In [12]:
s=s.drop(index=4)  #assiggnnment operator permanent change

In [13]:
s

0       red
1    orange
2      blue
3     green
Name: colours, dtype: object

In [14]:
l1=[10,20,100.7]   #to show homogenous conversion - so converted to str
pd.Series(l1)

0     10.0
1     20.0
2    100.7
dtype: float64

In [15]:
s[1:3]   #slicing|

1    orange
2      blue
Name: colours, dtype: object

In [16]:
s[::2]

0     red
2    blue
Name: colours, dtype: object

In [17]:
s[::-1]

3     green
2      blue
1    orange
0       red
Name: colours, dtype: object

## DataFrame Creation

In [18]:
d1={'name':['smmith','balke','clark','smith','miller'],
   'sal':[2000,3000,1000,2000,1000],
   'comm':[None,None,100,None,100],
   'deptno':[10.2,12.0,13.0,15.4,22.4],
   'hiredate':['12/dec/2026','1/jan/2022','2/feb/2005','3/sep/2023','5/may/2000']
}

#no of keys=No of columns
#no of list element=no of rows

In [19]:
df1=pd.DataFrame(d1)

In [20]:
df1

     name   sal   comm  deptno     hiredate
0  smmith  2000    NaN    10.2  12/dec/2026
1   balke  3000    NaN    12.0   1/jan/2022
2   clark  1000  100.0    13.0   2/feb/2005
3   smith  2000    NaN    15.4   3/sep/2023
4  miller  1000  100.0    22.4   5/may/2000

In [21]:
df1['name']

0    smmith
1     balke
2     clark
3     smith
4    miller
Name: name, dtype: object

In [22]:
df1.loc[0]

name             smmith
sal                2000
comm                NaN
deptno             10.2
hiredate    12/dec/2026
Name: 0, dtype: object

In [23]:
df1['bonus'] = df1['sal'] * 0.1
df1

     name   sal   comm  deptno     hiredate  bonus
0  smmith  2000    NaN    10.2  12/dec/2026  200.0
1   balke  3000    NaN    12.0   1/jan/2022  300.0
2   clark  1000  100.0    13.0   2/feb/2005  100.0
3   smith  2000    NaN    15.4   3/sep/2023  200.0
4  miller  1000  100.0    22.4   5/may/2000  100.0

In [24]:
df1.drop('comm', axis=1)

     name   sal  deptno     hiredate  bonus
0  smmith  2000    10.2  12/dec/2026  200.0
1   balke  3000    12.0   1/jan/2022  300.0
2   clark  1000    13.0   2/feb/2005  100.0
3   smith  2000    15.4   3/sep/2023  200.0
4  miller  1000    22.4   5/may/2000  100.0

In [25]:
df1.drop(index=0)

     name   sal   comm  deptno    hiredate  bonus
1   balke  3000    NaN    12.0  1/jan/2022  300.0
2   clark  1000  100.0    13.0  2/feb/2005  100.0
3   smith  2000    NaN    15.4  3/sep/2023  200.0
4  miller  1000  100.0    22.4  5/may/2000  100.0

In [26]:
df1[0:2]

     name   sal  comm  deptno     hiredate  bonus
0  smmith  2000   NaN    10.2  12/dec/2026  200.0
1   balke  3000   NaN    12.0   1/jan/2022  300.0

In [27]:
df1.shape

(5, 6)

In [28]:
df1.info

<bound method DataFrame.info of      name   sal   comm  deptno     hiredate  bonus
0  smmith  2000    NaN    10.2  12/dec/2026  200.0
1   balke  3000    NaN    12.0   1/jan/2022  300.0
2   clark  1000  100.0    13.0   2/feb/2005  100.0
3   smith  2000    NaN    15.4   3/sep/2023  200.0
4  miller  1000  100.0    22.4   5/may/2000  100.0>

In [29]:
d2={'name':['radha','shyam','ram','veena','sweta'],
   'sal':[4000,5000,3000,2000,4580],
   'comm':[None,None,100,None,500],
   'deptno':[13.9,25.9,79.6,57.0,48.7],
   'hiredate':['12/dec/2026','1/jan/2022','2/feb/2005','8/dec/2024','6/dec/2023']
}

In [30]:
df2=pd.DataFrame(d2)

In [31]:
df2

    name   sal   comm  deptno     hiredate
0  radha  4000    NaN    13.9  12/dec/2026
1  shyam  5000    NaN    25.9   1/jan/2022
2    ram  3000  100.0    79.6   2/feb/2005
3  veena  2000    NaN    57.0   8/dec/2024
4  sweta  4580  500.0    48.7   6/dec/2023

## Concat

In [32]:
pd.concat([df1,df2])     #concat( iterables )-add 2 dataframe          #axis=0(row)

     name   sal   comm  deptno     hiredate  bonus
0  smmith  2000    NaN    10.2  12/dec/2026  200.0
1   balke  3000    NaN    12.0   1/jan/2022  300.0
2   clark  1000  100.0    13.0   2/feb/2005  100.0
3   smith  2000    NaN    15.4   3/sep/2023  200.0
4  miller  1000  100.0    22.4   5/may/2000  100.0
0   radha  4000    NaN    13.9  12/dec/2026    NaN
1   shyam  5000    NaN    25.9   1/jan/2022    NaN
2     ram  3000  100.0    79.6   2/feb/2005    NaN
3   veena  2000    NaN    57.0   8/dec/2024    NaN
4   sweta  4580  500.0    48.7   6/dec/2023    NaN

In [33]:
df=pd.concat([df1,df2],axis=0)                                     #axis=0(row)

In [34]:
df.reset_index()    #to give new index value to the concat table

   index    name   sal   comm  deptno     hiredate  bonus
0      0  smmith  2000    NaN    10.2  12/dec/2026  200.0
1      1   balke  3000    NaN    12.0   1/jan/2022  300.0
2      2   clark  1000  100.0    13.0   2/feb/2005  100.0
3      3   smith  2000    NaN    15.4   3/sep/2023  200.0
4      4  miller  1000  100.0    22.4   5/may/2000  100.0
5      0   radha  4000    NaN    13.9  12/dec/2026    NaN
6      1   shyam  5000    NaN    25.9   1/jan/2022    NaN
7      2     ram  3000  100.0    79.6   2/feb/2005    NaN
8      3   veena  2000    NaN    57.0   8/dec/2024    NaN
9      4   sweta  4580  500.0    48.7   6/dec/2023    NaN

In [35]:
df=df.reset_index(drop=True)             #drop=True is used to remove old index

In [36]:
pd.concat([df1,df2],axis=1)                   #axis=1(column)

,name,sal,comm,deptno,hiredate,bonus,name,sal,comm,deptno,hiredate
0,smmith,2000,NaN,10.2,12/dec/2026,200.0,radha,4000,NaN,13.9,12/dec/2026
1,balke,3000,NaN,12.0,1/jan/2022,300.0,shyam,5000,NaN,25.9,1/jan/2022
2,clark,1000,100.0,13.0,2/feb/2005,100.0,ram,3000,100.0,79.6,2/feb/2005
3,smith,2000,NaN,15.4,3/sep/2023,200.0,veena,2000,NaN,57.0,8/dec/2024
4,miller,1000,100.0,22.4,5/may/2000,100.0,sweta,4580,500.0,48.7,6/dec/2023

In [37]:
df3=pd.DataFrame({'Column_1':[0]*10,
                  'column_2':[None]*10
})
df3

   Column_1 column_2
0         0     None
1         0     None
2         0     None
3         0     None
4         0     None
5         0     None
6         0     None
7         0     None
8         0     None
9         0     None

In [38]:
df=pd.concat([df,df3],axis=1)
df

     name   sal   comm  deptno     hiredate  bonus  Column_1 column_2
0  smmith  2000    NaN    10.2  12/dec/2026  200.0         0     None
1   balke  3000    NaN    12.0   1/jan/2022  300.0         0     None
2   clark  1000  100.0    13.0   2/feb/2005  100.0         0     None
3   smith  2000    NaN    15.4   3/sep/2023  200.0         0     None
4  miller  1000  100.0    22.4   5/may/2000  100.0         0     None
5   radha  4000    NaN    13.9  12/dec/2026    NaN         0     None
6   shyam  5000    NaN    25.9   1/jan/2022    NaN         0     None
7     ram  3000  100.0    79.6   2/feb/2005    NaN         0     None
8   veena  2000    NaN    57.0   8/dec/2024    NaN         0     None
9   sweta  4580  500.0    48.7   6/dec/2023    NaN         0     None

In [39]:

df.head()            #to get first 5

     name   sal   comm  deptno     hiredate  bonus  Column_1 column_2
0  smmith  2000    NaN    10.2  12/dec/2026  200.0         0     None
1   balke  3000    NaN    12.0   1/jan/2022  300.0         0     None
2   clark  1000  100.0    13.0   2/feb/2005  100.0         0     None
3   smith  2000    NaN    15.4   3/sep/2023  200.0         0     None
4  miller  1000  100.0    22.4   5/may/2000  100.0         0     None

In [40]:
df.head(7)

     name   sal   comm  deptno     hiredate  bonus  Column_1 column_2
0  smmith  2000    NaN    10.2  12/dec/2026  200.0         0     None
1   balke  3000    NaN    12.0   1/jan/2022  300.0         0     None
2   clark  1000  100.0    13.0   2/feb/2005  100.0         0     None
3   smith  2000    NaN    15.4   3/sep/2023  200.0         0     None
4  miller  1000  100.0    22.4   5/may/2000  100.0         0     None
5   radha  4000    NaN    13.9  12/dec/2026    NaN         0     None
6   shyam  5000    NaN    25.9   1/jan/2022    NaN         0     None

In [41]:
df.tail()        #to get last 5

    name   sal   comm  deptno     hiredate  bonus  Column_1 column_2
5  radha  4000    NaN    13.9  12/dec/2026    NaN         0     None
6  shyam  5000    NaN    25.9   1/jan/2022    NaN         0     None
7    ram  3000  100.0    79.6   2/feb/2005    NaN         0     None
8  veena  2000    NaN    57.0   8/dec/2024    NaN         0     None
9  sweta  4580  500.0    48.7   6/dec/2023    NaN         0     None

In [42]:
df.tail(7)

     name   sal   comm  deptno     hiredate  bonus  Column_1 column_2
3   smith  2000    NaN    15.4   3/sep/2023  200.0         0     None
4  miller  1000  100.0    22.4   5/may/2000  100.0         0     None
5   radha  4000    NaN    13.9  12/dec/2026    NaN         0     None
6   shyam  5000    NaN    25.9   1/jan/2022    NaN         0     None
7     ram  3000  100.0    79.6   2/feb/2005    NaN         0     None
8   veena  2000    NaN    57.0   8/dec/2024    NaN         0     None
9   sweta  4580  500.0    48.7   6/dec/2023    NaN         0     None

# loc[ ]

In [43]:
df.loc[0]                 #[row-based- index or list-of-index or row filtering conds ,   ->>>>it work like where
                                 #[col-based- single-col-name/list-of-col]-by de- select all col]     ->>>>it work like select

name             smmith
sal                2000
comm                NaN
deptno             10.2
hiredate    12/dec/2026
bonus             200.0
Column_1              0
column_2           None
Name: 0, dtype: object

In [44]:
df['sal']

0    2000
1    3000
2    1000
3    2000
4    1000
5    4000
6    5000
7    3000
8    2000
9    4580
Name: sal, dtype: int64

In [45]:
df['sal']>2000

0    False
1     True
2    False
3    False
4    False
5     True
6     True
7     True
8    False
9     True
Name: sal, dtype: bool

In [46]:
df.loc[df['sal']>2000]

    name   sal   comm  deptno     hiredate  bonus  Column_1 column_2
1  balke  3000    NaN    12.0   1/jan/2022  300.0         0     None
5  radha  4000    NaN    13.9  12/dec/2026    NaN         0     None
6  shyam  5000    NaN    25.9   1/jan/2022    NaN         0     None
7    ram  3000  100.0    79.6   2/feb/2005    NaN         0     None
9  sweta  4580  500.0    48.7   6/dec/2023    NaN         0     None

In [47]:
df.loc[df['sal']>2000,'name']

1    balke
5    radha
6    shyam
7      ram
9    sweta
Name: name, dtype: object

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   sal       10 non-null     int64
 2   comm      4 non-null      float64
 3   deptno    10 non-null     float64
 4   hiredate  10 non-null     object
 5   bonus     5 non-null      float64
 6   Column_1  10 non-null     int64
 7   column_2  0 non-null      object
dtypes: float64(3), int64(2), object(3)
memory usage: 772.0+ bytes

In [49]:
df.size

80

In [50]:
df.shape

(10, 8)

In [51]:
df.loc[[0,5,7]]

     name   sal   comm  deptno     hiredate  bonus  Column_1 column_2
0  smmith  2000    NaN    10.2  12/dec/2026  200.0         0     None
5   radha  4000    NaN    13.9  12/dec/2026    NaN         0     None
7     ram  3000  100.0    79.6   2/feb/2005    NaN         0     None

In [52]:
df.loc[[0,5,7],'name']

0    smmith
5     radha
7       ram
Name: name, dtype: object

In [53]:
df.loc[0:9:2]

     name   sal   comm  deptno     hiredate  bonus  Column_1 column_2
0  smmith  2000    NaN    10.2  12/dec/2026  200.0         0     None
2   clark  1000  100.0    13.0   2/feb/2005  100.0         0     None
4  miller  1000  100.0    22.4   5/may/2000  100.0         0     None
6   shyam  5000    NaN    25.9   1/jan/2022    NaN         0     None
8   veena  2000    NaN    57.0   8/dec/2024    NaN         0     None

In [54]:
df.loc[0:9:2,['name','sal']]

     name   sal
0  smmith  2000
2   clark  1000
4  miller  1000
6   shyam  5000
8   veena  2000

# info()

In [55]:
df

     name   sal   comm  deptno     hiredate  bonus  Column_1 column_2
0  smmith  2000    NaN    10.2  12/dec/2026  200.0         0     None
1   balke  3000    NaN    12.0   1/jan/2022  300.0         0     None
2   clark  1000  100.0    13.0   2/feb/2005  100.0         0     None
3   smith  2000    NaN    15.4   3/sep/2023  200.0         0     None
4  miller  1000  100.0    22.4   5/may/2000  100.0         0     None
5   radha  4000    NaN    13.9  12/dec/2026    NaN         0     None
6   shyam  5000    NaN    25.9   1/jan/2022    NaN         0     None
7     ram  3000  100.0    79.6   2/feb/2005    NaN         0     None
8   veena  2000    NaN    57.0   8/dec/2024    NaN         0     None
9   sweta  4580  500.0    48.7   6/dec/2023    NaN         0     None

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   sal       10 non-null     int64
 2   comm      4 non-null      float64
 3   deptno    10 non-null     float64
 4   hiredate  10 non-null     object
 5   bonus     5 non-null      float64
 6   Column_1  10 non-null     int64
 7   column_2  0 non-null      object
dtypes: float64(3), int64(2), object(3)
memory usage: 772.0+ bytes

In [58]:
df=pd.read_csv('emp.csv')

In [59]:
df.to_csv('emp.csv',index=True)

# Understanding the dataset

In [65]:
df.columns

Index(['Unnamed: 0', 'name', 'sal', 'comm', 'deptno', 'hiredate', 'bonus',
       'Column_1', 'column_2'],
      dtype='object')

In [66]:
df.info

<bound method DataFrame.info of    Unnamed: 0    name   sal   comm  deptno     hiredate  bonus  Column_1  \
0           0  smmith  2000    NaN    10.2  12/dec/2026  200.0         0
1           1   balke  3000    NaN    12.0   1/jan/2022  300.0         0
2           2   clark  1000  100.0    13.0   2/feb/2005  100.0         0
3           3   smith  2000    NaN    15.4   3/sep/2023  200.0         0
4           4  miller  1000  100.0    22.4   5/may/2000  100.0         0
5           5   radha  4000    NaN    13.9  12/dec/2026    NaN         0
6           6   shyam  5000    NaN    25.9   1/jan/2022    NaN         0
7           7     ram  3000  100.0    79.6   2/feb/2005    NaN         0
8           8   veena  2000    NaN    57.0   8/dec/2024    NaN         0
9           9   sweta  4580  500.0    48.7   6/dec/2023    NaN         0

   column_2
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN  >

In [67]:
df.head()

,Unnamed: 0,name,sal,comm,deptno,hiredate,bonus,Column_1,column_2
0,0,smmith,2000,NaN,10.2,12/dec/2026,200.0,0,NaN
1,1,balke,3000,NaN,12.0,1/jan/2022,300.0,0,NaN
2,2,clark,1000,100.0,13.0,2/feb/2005,100.0,0,NaN
3,3,smith,2000,NaN,15.4,3/sep/2023,200.0,0,NaN
4,4,miller,1000,100.0,22.4,5/may/2000,100.0,0,NaN

# Data Cleaning
1. Check for dublicates and handling
2. Check for missing values and handle it
3. Check for invalid dtype column and handle it.
4. Check for the unnecessary column and drop it.

In [69]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [71]:
df.duplicated().any()

np.False_

In [72]:
df.duplicated().all()

np.False_

In [74]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates()            #remove first duplicates

,Unnamed: 0,name,sal,comm,deptno,hiredate,bonus,Column_1,column_2
0,0,smmith,2000,NaN,10.2,12/dec/2026,200.0,0,NaN
1,1,balke,3000,NaN,12.0,1/jan/2022,300.0,0,NaN
2,2,clark,1000,100.0,13.0,2/feb/2005,100.0,0,NaN
3,3,smith,2000,NaN,15.4,3/sep/2023,200.0,0,NaN
4,4,miller,1000,100.0,22.4,5/may/2000,100.0,0,NaN
5,5,radha,4000,NaN,13.9,12/dec/2026,NaN,0,NaN
6,6,shyam,5000,NaN,25.9,1/jan/2022,NaN,0,NaN
7,7,ram,3000,100.0,79.6,2/feb/2005,NaN,0,NaN
8,8,veena,2000,NaN,57.0,8/dec/2024,NaN,0,NaN
9,9,sweta,4580,500.0,48.7,6/dec/2023,NaN,0,NaN

In [76]:
df.drop_duplicates(keep='last')

,Unnamed: 0,name,sal,comm,deptno,hiredate,bonus,Column_1,column_2
0,0,smmith,2000,NaN,10.2,12/dec/2026,200.0,0,NaN
1,1,balke,3000,NaN,12.0,1/jan/2022,300.0,0,NaN
2,2,clark,1000,100.0,13.0,2/feb/2005,100.0,0,NaN
3,3,smith,2000,NaN,15.4,3/sep/2023,200.0,0,NaN
4,4,miller,1000,100.0,22.4,5/may/2000,100.0,0,NaN
5,5,radha,4000,NaN,13.9,12/dec/2026,NaN,0,NaN
6,6,shyam,5000,NaN,25.9,1/jan/2022,NaN,0,NaN
7,7,ram,3000,100.0,79.6,2/feb/2005,NaN,0,NaN
8,8,veena,2000,NaN,57.0,8/dec/2024,NaN,0,NaN
9,9,sweta,4580,500.0,48.7,6/dec/2023,NaN,0,NaN

In [77]:
df.drop_duplicates()

,Unnamed: 0,name,sal,comm,deptno,hiredate,bonus,Column_1,column_2
0,0,smmith,2000,NaN,10.2,12/dec/2026,200.0,0,NaN
1,1,balke,3000,NaN,12.0,1/jan/2022,300.0,0,NaN
2,2,clark,1000,100.0,13.0,2/feb/2005,100.0,0,NaN
3,3,smith,2000,NaN,15.4,3/sep/2023,200.0,0,NaN
4,4,miller,1000,100.0,22.4,5/may/2000,100.0,0,NaN
5,5,radha,4000,NaN,13.9,12/dec/2026,NaN,0,NaN
6,6,shyam,5000,NaN,25.9,1/jan/2022,NaN,0,NaN
7,7,ram,3000,100.0,79.6,2/feb/2005,NaN,0,NaN
8,8,veena,2000,NaN,57.0,8/dec/2024,NaN,0,NaN
9,9,sweta,4580,500.0,48.7,6/dec/2023,NaN,0,NaN

In [78]:
df=df.reset_index(drop=True)