In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('titanic.csv')

In [3]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [4]:
df.tail(1)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1308,3,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.875,NaN,S,0

In [5]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1304    False
1305    False
1306    False
1307    False
1308    False
Length: 1309, dtype: bool

In [6]:
df.duplicated().any()

np.False_

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

sipsb--->siblings & spouse

parch--->parents & children

fare-->ticket price

cabin-->location of compartment

embarked-->boarding point

In [8]:
df

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [9]:
age_mean=df['age'].mean()       #to fill null values-->use mean, mode

In [10]:
fare_mean=df['fare'].mean()            #embarked is str ---> cannot fnd mean(only for number)
                                #cabin  more number of null-->not necessary

In [11]:
df['embarked'].unique()                     #embarked is str ---> cannot fnd mean(only for number) so find 1.unique, 2.mode

array(['S', 'C', nan, 'Q'], dtype=object)

In [12]:
embarked_mode=df['embarked'].mode()[0]           #first most repeated -->[0]

In [13]:
df['age']=df['age'].fillna(age_mean)         #to fill null values
df['fare']=df['fare'].fillna(fare_mean)
df['embarked']=df['embarked'].fillna(embarked_mode)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1309 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1309 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1309 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [15]:
#cabin has more null values
df=df.dropna(axis=1)    #axis=1--->(row)
                     #axis=0--->(col)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1309 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1309 non-null   float64
 8   embarked  1309 non-null   object
 9   survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(4)
memory usage: 102.4+ KB

In [17]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,S,0

In [18]:
df['pclass'].unique()

array([1, 2, 3])

In [19]:
#split name as 1st name and last name  use-->#split but split is str method  
                                             #expand-->conert it into table
                                             #make 2 diff col as 1st name and last name -->2 name so 2D format
df[['F_name','L_name']]=df['name'].str.split(',',expand=True)

In [20]:
df.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,S,1,Allen,Miss. Elisabeth Walton
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,S,1,Allison,Master. Hudson Trevor
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,S,0,Allison,Miss. Helen Loraine
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,S,0,Allison,Mr. Hudson Joshua Creighton
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,S,0,Allison,Mrs. Hudson J C (Bessie Waldo Daniels)

In [21]:
df=df.drop(columns='name')

In [22]:
df[['Title','L_name']]=df['L_name'].str.split('.',expand=True,n=1)

In [23]:
df.head()

,pclass,sex,age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title
0,1,female,29.0000,0,0,24160,211.3375,S,1,Allen,Elisabeth Walton,Miss
1,1,male,0.9167,1,2,113781,151.5500,S,1,Allison,Hudson Trevor,Master
2,1,female,2.0000,1,2,113781,151.5500,S,0,Allison,Helen Loraine,Miss
3,1,male,30.0000,1,2,113781,151.5500,S,0,Allison,Hudson Joshua Creighton,Mr
4,1,female,25.0000,1,2,113781,151.5500,S,0,Allison,Hudson J C (Bessie Waldo Daniels),Mrs

In [24]:
#remove end space-->strip method
df['Title']=df['Title'].str.strip()
df['F_name']=df['F_name'].str.strip()

In [25]:
df

,pclass,sex,age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title
0,1,female,29.000000,0,0,24160,211.3375,S,1,Allen,Elisabeth Walton,Miss
1,1,male,0.916700,1,2,113781,151.5500,S,1,Allison,Hudson Trevor,Master
2,1,female,2.000000,1,2,113781,151.5500,S,0,Allison,Helen Loraine,Miss
3,1,male,30.000000,1,2,113781,151.5500,S,0,Allison,Hudson Joshua Creighton,Mr
4,1,female,25.000000,1,2,113781,151.5500,S,0,Allison,Hudson J C (Bessie Waldo Daniels),Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,female,14.500000,1,0,2665,14.4542,C,0,Zabour,Hileni,Miss
1305,3,female,29.881135,1,0,2665,14.4542,C,0,Zabour,Thamine,Miss
1306,3,male,26.500000,0,0,2656,7.2250,C,0,Zakarian,Mapriededer,Mr
1307,3,male,27.000000,0,0,2670,7.2250,C,0,Zakarian,Ortin,Mr
1308,3,male,29.000000,0,0,315082,7.8750,S,0,Zimmerman,Leo,Mr

In [26]:
#rename col sex-gender -->rename
df=df.rename(columns={'sex':'Gender'})

In [27]:
df=df.rename(columns={'age':'Age'})

In [28]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title
0,1,female,29.000000,0,0,24160,211.3375,S,1,Allen,Elisabeth Walton,Miss
1,1,male,0.916700,1,2,113781,151.5500,S,1,Allison,Hudson Trevor,Master
2,1,female,2.000000,1,2,113781,151.5500,S,0,Allison,Helen Loraine,Miss
3,1,male,30.000000,1,2,113781,151.5500,S,0,Allison,Hudson Joshua Creighton,Mr
4,1,female,25.000000,1,2,113781,151.5500,S,0,Allison,Hudson J C (Bessie Waldo Daniels),Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,female,14.500000,1,0,2665,14.4542,C,0,Zabour,Hileni,Miss
1305,3,female,29.881135,1,0,2665,14.4542,C,0,Zabour,Thamine,Miss
1306,3,male,26.500000,0,0,2656,7.2250,C,0,Zakarian,Mapriededer,Mr
1307,3,male,27.000000,0,0,2670,7.2250,C,0,Zakarian,Ortin,Mr
1308,3,male,29.000000,0,0,315082,7.8750,S,0,Zimmerman,Leo,Mr

In [29]:
#first char -upper case---->capitalize   - str method  (capitalize used for row|) & (rename used for columns capitalize----)
df['Gender']=df['Gender'].str.capitalize()

In [30]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title
0,1,Female,29.000000,0,0,24160,211.3375,S,1,Allen,Elisabeth Walton,Miss
1,1,Male,0.916700,1,2,113781,151.5500,S,1,Allison,Hudson Trevor,Master
2,1,Female,2.000000,1,2,113781,151.5500,S,0,Allison,Helen Loraine,Miss
3,1,Male,30.000000,1,2,113781,151.5500,S,0,Allison,Hudson Joshua Creighton,Mr
4,1,Female,25.000000,1,2,113781,151.5500,S,0,Allison,Hudson J C (Bessie Waldo Daniels),Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,Female,14.500000,1,0,2665,14.4542,C,0,Zabour,Hileni,Miss
1305,3,Female,29.881135,1,0,2665,14.4542,C,0,Zabour,Thamine,Miss
1306,3,Male,26.500000,0,0,2656,7.2250,C,0,Zakarian,Mapriededer,Mr
1307,3,Male,27.000000,0,0,2670,7.2250,C,0,Zakarian,Ortin,Mr
1308,3,Male,29.000000,0,0,315082,7.8750,S,0,Zimmerman,Leo,Mr

In [31]:
df['Age']=df['Age'].round(1)

In [32]:
df       #sibling&spouse   #parent&child are same family count

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title
0,1,Female,29.0,0,0,24160,211.3375,S,1,Allen,Elisabeth Walton,Miss
1,1,Male,0.9,1,2,113781,151.5500,S,1,Allison,Hudson Trevor,Master
2,1,Female,2.0,1,2,113781,151.5500,S,0,Allison,Helen Loraine,Miss
3,1,Male,30.0,1,2,113781,151.5500,S,0,Allison,Hudson Joshua Creighton,Mr
4,1,Female,25.0,1,2,113781,151.5500,S,0,Allison,Hudson J C (Bessie Waldo Daniels),Mrs
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,Female,14.5,1,0,2665,14.4542,C,0,Zabour,Hileni,Miss
1305,3,Female,29.9,1,0,2665,14.4542,C,0,Zabour,Thamine,Miss
1306,3,Male,26.5,0,0,2656,7.2250,C,0,Zakarian,Mapriededer,Mr
1307,3,Male,27.0,0,0,2670,7.2250,C,0,Zakarian,Ortin,Mr
1308,3,Male,29.0,0,0,315082,7.8750,S,0,Zimmerman,Leo,Mr

In [33]:
df['Their_family_count']=df['sibsp']+df['parch']

In [34]:
df    #ticket is ticket number

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count
0,1,Female,29.0,0,0,24160,211.3375,S,1,Allen,Elisabeth Walton,Miss,0
1,1,Male,0.9,1,2,113781,151.5500,S,1,Allison,Hudson Trevor,Master,3
2,1,Female,2.0,1,2,113781,151.5500,S,0,Allison,Helen Loraine,Miss,3
3,1,Male,30.0,1,2,113781,151.5500,S,0,Allison,Hudson Joshua Creighton,Mr,3
4,1,Female,25.0,1,2,113781,151.5500,S,0,Allison,Hudson J C (Bessie Waldo Daniels),Mrs,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,Female,14.5,1,0,2665,14.4542,C,0,Zabour,Hileni,Miss,1
1305,3,Female,29.9,1,0,2665,14.4542,C,0,Zabour,Thamine,Miss,1
1306,3,Male,26.5,0,0,2656,7.2250,C,0,Zakarian,Mapriededer,Mr,0
1307,3,Male,27.0,0,0,2670,7.2250,C,0,Zakarian,Ortin,Mr,0
1308,3,Male,29.0,0,0,315082,7.8750,S,0,Zimmerman,Leo,Mr,0

In [35]:
df['fare']=df['fare'].round(1)

In [36]:
df        #embarked col we only have starting letter of boarding points name

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count
0,1,Female,29.0,0,0,24160,211.3,S,1,Allen,Elisabeth Walton,Miss,0
1,1,Male,0.9,1,2,113781,151.6,S,1,Allison,Hudson Trevor,Master,3
2,1,Female,2.0,1,2,113781,151.6,S,0,Allison,Helen Loraine,Miss,3
3,1,Male,30.0,1,2,113781,151.6,S,0,Allison,Hudson Joshua Creighton,Mr,3
4,1,Female,25.0,1,2,113781,151.6,S,0,Allison,Hudson J C (Bessie Waldo Daniels),Mrs,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,Female,14.5,1,0,2665,14.5,C,0,Zabour,Hileni,Miss,1
1305,3,Female,29.9,1,0,2665,14.5,C,0,Zabour,Thamine,Miss,1
1306,3,Male,26.5,0,0,2656,7.2,C,0,Zakarian,Mapriededer,Mr,0
1307,3,Male,27.0,0,0,2670,7.2,C,0,Zakarian,Ortin,Mr,0
1308,3,Male,29.0,0,0,315082,7.9,S,0,Zimmerman,Leo,Mr,0

In [37]:
df['embarked'].unique()          #we have only 3 debording places #s-southampton
                                                                  #c-cherbourge
                                                                  #q-queenstown

array(['S', 'C', 'Q'], dtype=object)

In [38]:
d={'S':'Southampton','C':'Cherbourge','Q':'Queenstown'}
df['embarked']=df['embarked'].replace(d)

In [39]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count
0,1,Female,29.0,0,0,24160,211.3,Southampton,1,Allen,Elisabeth Walton,Miss,0
1,1,Male,0.9,1,2,113781,151.6,Southampton,1,Allison,Hudson Trevor,Master,3
2,1,Female,2.0,1,2,113781,151.6,Southampton,0,Allison,Helen Loraine,Miss,3
3,1,Male,30.0,1,2,113781,151.6,Southampton,0,Allison,Hudson Joshua Creighton,Mr,3
4,1,Female,25.0,1,2,113781,151.6,Southampton,0,Allison,Hudson J C (Bessie Waldo Daniels),Mrs,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,Female,14.5,1,0,2665,14.5,Cherbourge,0,Zabour,Hileni,Miss,1
1305,3,Female,29.9,1,0,2665,14.5,Cherbourge,0,Zabour,Thamine,Miss,1
1306,3,Male,26.5,0,0,2656,7.2,Cherbourge,0,Zakarian,Mapriededer,Mr,0
1307,3,Male,27.0,0,0,2670,7.2,Cherbourge,0,Zakarian,Ortin,Mr,0
1308,3,Male,29.0,0,0,315082,7.9,Southampton,0,Zimmerman,Leo,Mr,0

In [40]:
#sort the record - based on ticket col
df=df.sort_values(by=['ticket','Age'], ascending=[True,True])

In [41]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count
195,1,Female,16.0,0,0,110152,86.5,Southampton,1,Maioni,Roberta,Miss,0
67,1,Female,30.0,0,0,110152,86.5,Southampton,1,Cherry,Gladys,Miss,0
245,1,Female,33.0,0,0,110152,86.5,Southampton,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,0
289,1,Female,18.0,0,2,110413,79.6,Southampton,1,Taussig,Ruth,Miss,2
291,1,Female,39.0,1,1,110413,79.6,Southampton,1,Taussig,Emil (Tillie Mandelbaum),Mrs,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,1,Male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,Chaffee,Herbert Fuller,Mr,1
63,1,Female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,Chaffee,Herbert Fuller (Carrie Constance Toogood),Mrs,1
433,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,Harris,Walter,Mr,0
82,1,Female,36.0,0,2,WE/P 5735,71.0,Southampton,1,Crosby,Harriet R,Miss,2
81,1,Male,70.0,1,1,WE/P 5735,71.0,Southampton,0,Crosby,Edward Gifford,Capt,2

In [42]:
#proper index
df=df.reset_index(drop=True)

In [43]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count
0,1,Female,16.0,0,0,110152,86.5,Southampton,1,Maioni,Roberta,Miss,0
1,1,Female,30.0,0,0,110152,86.5,Southampton,1,Cherry,Gladys,Miss,0
2,1,Female,33.0,0,0,110152,86.5,Southampton,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,0
3,1,Female,18.0,0,2,110413,79.6,Southampton,1,Taussig,Ruth,Miss,2
4,1,Female,39.0,1,1,110413,79.6,Southampton,1,Taussig,Emil (Tillie Mandelbaum),Mrs,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,Chaffee,Herbert Fuller,Mr,1
1305,1,Female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,Chaffee,Herbert Fuller (Carrie Constance Toogood),Mrs,1
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,Harris,Walter,Mr,0
1307,1,Female,36.0,0,2,WE/P 5735,71.0,Southampton,1,Crosby,Harriet R,Miss,2
1308,1,Male,70.0,1,1,WE/P 5735,71.0,Southampton,0,Crosby,Edward Gifford,Capt,2

In [44]:
#to check how many passangers are sharing same ticket
df['ticket'].value_counts()

ticket
CA. 2343            11
CA 2144              8
1601                 8
S.O.C. 14879         7
347082               7
                    ..
SOTON/O2 3101272     1
STON/O2. 3101283     1
STON/O2. 3101282     1
STON/O2. 3101271     1
112050               1
Name: count, Length: 929, dtype: int64

In [45]:
df['ticket'].value_counts().reset_index()

               ticket  count
0            CA. 2343     11
1             CA 2144      8
2                1601      8
3        S.O.C. 14879      7
4              347082      7
..                ...    ...
924  SOTON/O2 3101272      1
925  STON/O2. 3101283      1
926  STON/O2. 3101282      1
927  STON/O2. 3101271      1
928            112050      1

[929 rows x 2 columns]

In [46]:
ticket_passanger=df['ticket'].value_counts().reset_index(name='Number_of_Passager')   #to name count as number of passangers

In [47]:
ticket_passanger

               ticket  Number_of_Passager
0            CA. 2343                  11
1             CA 2144                   8
2                1601                   8
3        S.O.C. 14879                   7
4              347082                   7
..                ...                 ...
924  SOTON/O2 3101272                   1
925  STON/O2. 3101283                   1
926  STON/O2. 3101282                   1
927  STON/O2. 3101271                   1
928            112050                   1

[929 rows x 2 columns]

In [48]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count
0,1,Female,16.0,0,0,110152,86.5,Southampton,1,Maioni,Roberta,Miss,0
1,1,Female,30.0,0,0,110152,86.5,Southampton,1,Cherry,Gladys,Miss,0
2,1,Female,33.0,0,0,110152,86.5,Southampton,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,0
3,1,Female,18.0,0,2,110413,79.6,Southampton,1,Taussig,Ruth,Miss,2
4,1,Female,39.0,1,1,110413,79.6,Southampton,1,Taussig,Emil (Tillie Mandelbaum),Mrs,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,Chaffee,Herbert Fuller,Mr,1
1305,1,Female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,Chaffee,Herbert Fuller (Carrie Constance Toogood),Mrs,1
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,Harris,Walter,Mr,0
1307,1,Female,36.0,0,2,WE/P 5735,71.0,Southampton,1,Crosby,Harriet R,Miss,2
1308,1,Male,70.0,1,1,WE/P 5735,71.0,Southampton,0,Crosby,Edward Gifford,Capt,2

In [49]:
#family_count means they are not family means they are friends or neighbour
# pd.merge(on=tikcet, left_on=ticket_no, right_on=, how='inner'/'outer'/'left'/'right');        #both have ticket col

df=pd.merge(df,ticket_passanger,on='ticket',how='inner')

In [50]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count,Number_of_Passager
0,1,Female,16.0,0,0,110152,86.5,Southampton,1,Maioni,Roberta,Miss,0,3
1,1,Female,30.0,0,0,110152,86.5,Southampton,1,Cherry,Gladys,Miss,0,3
2,1,Female,33.0,0,0,110152,86.5,Southampton,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,0,3
3,1,Female,18.0,0,2,110413,79.6,Southampton,1,Taussig,Ruth,Miss,2,3
4,1,Female,39.0,1,1,110413,79.6,Southampton,1,Taussig,Emil (Tillie Mandelbaum),Mrs,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,Chaffee,Herbert Fuller,Mr,1,2
1305,1,Female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,Chaffee,Herbert Fuller (Carrie Constance Toogood),Mrs,1,2
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,Harris,Walter,Mr,0,1
1307,1,Female,36.0,0,2,WE/P 5735,71.0,Southampton,1,Crosby,Harriet R,Miss,2,2
1308,1,Male,70.0,1,1,WE/P 5735,71.0,Southampton,0,Crosby,Edward Gifford,Capt,2,2

In [51]:
df          #ticket number 3 people have same ticket famcount-0 and number of pass-3

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count,Number_of_Passager
0,1,Female,16.0,0,0,110152,86.5,Southampton,1,Maioni,Roberta,Miss,0,3
1,1,Female,30.0,0,0,110152,86.5,Southampton,1,Cherry,Gladys,Miss,0,3
2,1,Female,33.0,0,0,110152,86.5,Southampton,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,0,3
3,1,Female,18.0,0,2,110413,79.6,Southampton,1,Taussig,Ruth,Miss,2,3
4,1,Female,39.0,1,1,110413,79.6,Southampton,1,Taussig,Emil (Tillie Mandelbaum),Mrs,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Male,46.0,1,0,W.E.P. 5734,61.2,Southampton,0,Chaffee,Herbert Fuller,Mr,1,2
1305,1,Female,47.0,1,0,W.E.P. 5734,61.2,Southampton,1,Chaffee,Herbert Fuller (Carrie Constance Toogood),Mrs,1,2
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,Harris,Walter,Mr,0,1
1307,1,Female,36.0,0,2,WE/P 5735,71.0,Southampton,1,Crosby,Harriet R,Miss,2,2
1308,1,Male,70.0,1,1,WE/P 5735,71.0,Southampton,0,Crosby,Edward Gifford,Capt,2,2

In [52]:
df['fare']=(df['fare']/df['Number_of_Passager']).round(1)

In [53]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count,Number_of_Passager
0,1,Female,16.0,0,0,110152,28.8,Southampton,1,Maioni,Roberta,Miss,0,3
1,1,Female,30.0,0,0,110152,28.8,Southampton,1,Cherry,Gladys,Miss,0,3
2,1,Female,33.0,0,0,110152,28.8,Southampton,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,0,3
3,1,Female,18.0,0,2,110413,26.5,Southampton,1,Taussig,Ruth,Miss,2,3
4,1,Female,39.0,1,1,110413,26.5,Southampton,1,Taussig,Emil (Tillie Mandelbaum),Mrs,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Male,46.0,1,0,W.E.P. 5734,30.6,Southampton,0,Chaffee,Herbert Fuller,Mr,1,2
1305,1,Female,47.0,1,0,W.E.P. 5734,30.6,Southampton,1,Chaffee,Herbert Fuller (Carrie Constance Toogood),Mrs,1,2
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,Harris,Walter,Mr,0,1
1307,1,Female,36.0,0,2,WE/P 5735,35.5,Southampton,1,Crosby,Harriet R,Miss,2,2
1308,1,Male,70.0,1,1,WE/P 5735,35.5,Southampton,0,Crosby,Edward Gifford,Capt,2,2

In [54]:
def comp_type(row):
    fam=row['Their_family_count']
    pas=row['Number_of_Passager']
    if pas==1:
        return 'Solo'
    elif fam==0 and pas>1:
        return 'Friends'
    else:
        return 'Family'

In [55]:
df['Companion_type']=df.apply(comp_type, axis=1)

In [56]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count,Number_of_Passager,Companion_type
0,1,Female,16.0,0,0,110152,28.8,Southampton,1,Maioni,Roberta,Miss,0,3,Friends
1,1,Female,30.0,0,0,110152,28.8,Southampton,1,Cherry,Gladys,Miss,0,3,Friends
2,1,Female,33.0,0,0,110152,28.8,Southampton,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,0,3,Friends
3,1,Female,18.0,0,2,110413,26.5,Southampton,1,Taussig,Ruth,Miss,2,3,Family
4,1,Female,39.0,1,1,110413,26.5,Southampton,1,Taussig,Emil (Tillie Mandelbaum),Mrs,2,3,Family
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Male,46.0,1,0,W.E.P. 5734,30.6,Southampton,0,Chaffee,Herbert Fuller,Mr,1,2,Family
1305,1,Female,47.0,1,0,W.E.P. 5734,30.6,Southampton,1,Chaffee,Herbert Fuller (Carrie Constance Toogood),Mrs,1,2,Family
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,Harris,Walter,Mr,0,1,Solo
1307,1,Female,36.0,0,2,WE/P 5735,35.5,Southampton,1,Crosby,Harriet R,Miss,2,2,Family
1308,1,Male,70.0,1,1,WE/P 5735,35.5,Southampton,0,Crosby,Edward Gifford,Capt,2,2,Family

In [57]:
def Age(row):
    if Age>0 and Age<=2:
        return "Infant"
    elif Age>2 and Age<=16:
        return "Child"
    elif Age>16 and Age<=25:
        return "Teen"
    elif Age>25 and Age<=59:
        return "adults"
    elif Age>59 and Age<=100:
        return "Seniour"

In [58]:
df['Age_group']=pd.cut(df['Age'],bins=[0,2,16,25,59,100],labels=["Infant","Child","Teen","adults","Seniour"])

In [59]:
df.head(1000)         #social status for like dr., .....

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count,Number_of_Passager,Companion_type,Age_group
0,1,Female,16.0,0,0,110152,28.8,Southampton,1,Maioni,Roberta,Miss,0,3,Friends,Child
1,1,Female,30.0,0,0,110152,28.8,Southampton,1,Cherry,Gladys,Miss,0,3,Friends,adults
2,1,Female,33.0,0,0,110152,28.8,Southampton,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,0,3,Friends,adults
3,1,Female,18.0,0,2,110413,26.5,Southampton,1,Taussig,Ruth,Miss,2,3,Family,Teen
4,1,Female,39.0,1,1,110413,26.5,Southampton,1,Taussig,Emil (Tillie Mandelbaum),Mrs,2,3,Family,adults
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,Male,29.9,0,0,A/S 2816,8.0,Southampton,0,Maisner,Simon,Mr,0,1,Solo,adults
996,3,Male,29.9,0,0,A4. 54510,8.0,Southampton,0,Moore,Leonard Charles,Mr,0,1,Solo,adults
997,3,Female,17.0,0,0,AQ/3. 30631,7.7,Queenstown,0,Hagardon,Kate,Miss,0,1,Solo,Teen
998,3,Male,29.9,0,0,AQ/4 3130,7.8,Queenstown,0,Mahon,John,Mr,0,1,Solo,adults
999,3,Male,9.0,0,1,C 17368,3.2,Southampton,1,Olsen,Artur Karl,Master,1,1,Solo,Child

In [60]:
df['Title'].unique()

array(['Miss', 'the Countess', 'Mrs', 'Mr', 'Dr', 'Major', 'Master',
       'Col', 'Lady', 'Jonkheer', 'Rev', 'Ms', 'Mme', 'Mlle', 'Sir',
       'Don', 'Dona', 'Capt'], dtype=object)

In [61]:
Royals=['the Countess','Jonkheer', 'Don', 'Dona', 'Master']
Common=[ 'Mrs', 'Mr', 'Ms', 'Mme','Lady', 'Mlle' ,'Sir','Miss']
Millitary=[ 'Major', 'Master', 'Capt', 'Col']
other_professionals=['Dr','Rev']

In [62]:
def Social_Status(row):
    c=row['Title']
    if c in Royals:
        return 'Royality'
    elif c in Common:
        return 'Common'
    elif c in Millitary:
        return 'Millitary'
    elif c in other_professionals:
        return 'other_professionals'

In [63]:
df['Social_Status']=df.apply(Social_Status,axis=1)

In [64]:
df

,pclass,Gender,Age,sibsp,parch,ticket,fare,embarked,survived,F_name,L_name,Title,Their_family_count,Number_of_Passager,Companion_type,Age_group,Social_Status
0,1,Female,16.0,0,0,110152,28.8,Southampton,1,Maioni,Roberta,Miss,0,3,Friends,Child,Common
1,1,Female,30.0,0,0,110152,28.8,Southampton,1,Cherry,Gladys,Miss,0,3,Friends,adults,Common
2,1,Female,33.0,0,0,110152,28.8,Southampton,1,Rothes,of (Lucy Noel Martha Dyer-Edwards),the Countess,0,3,Friends,adults,Royality
3,1,Female,18.0,0,2,110413,26.5,Southampton,1,Taussig,Ruth,Miss,2,3,Family,Teen,Common
4,1,Female,39.0,1,1,110413,26.5,Southampton,1,Taussig,Emil (Tillie Mandelbaum),Mrs,2,3,Family,adults,Common
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Male,46.0,1,0,W.E.P. 5734,30.6,Southampton,0,Chaffee,Herbert Fuller,Mr,1,2,Family,adults,Common
1305,1,Female,47.0,1,0,W.E.P. 5734,30.6,Southampton,1,Chaffee,Herbert Fuller (Carrie Constance Toogood),Mrs,1,2,Family,adults,Common
1306,2,Male,30.0,0,0,W/C 14208,10.5,Southampton,0,Harris,Walter,Mr,0,1,Solo,adults,Common
1307,1,Female,36.0,0,2,WE/P 5735,35.5,Southampton,1,Crosby,Harriet R,Miss,2,2,Family,adults,Common
1308,1,Male,70.0,1,1,WE/P 5735,35.5,Southampton,0,Crosby,Edward Gifford,Capt,2,2,Family,Seniour,Millitary

In [65]:
df.columns

Index(['pclass', 'Gender', 'Age', 'sibsp', 'parch', 'ticket', 'fare',
       'embarked', 'survived', 'F_name', 'L_name', 'Title',
       'Their_family_count', 'Number_of_Passager', 'Companion_type',
       'Age_group', 'Social_Status'],
      dtype='object')

In [66]:
#arrange in order
column_list=['pclass','Title', 'F_name', 'L_name', 'sibsp', 'parch','Gender', 'Age', 'fare','ticket','Their_family_count', 'Number_of_Passager', 'Companion_type','embarked', 'Age_group', 'Social_Status','survived' ]

In [67]:
df=df[column_list]

In [68]:
df

,pclass,Title,F_name,L_name,sibsp,parch,Gender,Age,fare,ticket,Their_family_count,Number_of_Passager,Companion_type,embarked,Age_group,Social_Status,survived
0,1,Miss,Maioni,Roberta,0,0,Female,16.0,28.8,110152,0,3,Friends,Southampton,Child,Common,1
1,1,Miss,Cherry,Gladys,0,0,Female,30.0,28.8,110152,0,3,Friends,Southampton,adults,Common,1
2,1,the Countess,Rothes,of (Lucy Noel Martha Dyer-Edwards),0,0,Female,33.0,28.8,110152,0,3,Friends,Southampton,adults,Royality,1
3,1,Miss,Taussig,Ruth,0,2,Female,18.0,26.5,110413,2,3,Family,Southampton,Teen,Common,1
4,1,Mrs,Taussig,Emil (Tillie Mandelbaum),1,1,Female,39.0,26.5,110413,2,3,Family,Southampton,adults,Common,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1,Mr,Chaffee,Herbert Fuller,1,0,Male,46.0,30.6,W.E.P. 5734,1,2,Family,Southampton,adults,Common,0
1305,1,Mrs,Chaffee,Herbert Fuller (Carrie Constance Toogood),1,0,Female,47.0,30.6,W.E.P. 5734,1,2,Family,Southampton,adults,Common,1
1306,2,Mr,Harris,Walter,0,0,Male,30.0,10.5,W/C 14208,0,1,Solo,Southampton,adults,Common,0
1307,1,Miss,Crosby,Harriet R,0,2,Female,36.0,35.5,WE/P 5735,2,2,Family,Southampton,adults,Common,1
1308,1,Capt,Crosby,Edward Gifford,1,1,Male,70.0,35.5,WE/P 5735,2,2,Family,Southampton,Seniour,Millitary,0

In [69]:
df.describe().round(1)      #give stastical info

,pclass,sibsp,parch,Age,fare,Their_family_count,Number_of_Passager,survived
count,1309.0,1309.0,1309.0,1309.0,1309.0,1309.0,1309.0,1309.0
mean,2.3,0.5,0.4,29.9,14.8,0.9,2.1,0.4
std,0.8,1.0,0.9,12.9,13.6,1.6,1.8,0.5
min,1.0,0.0,0.0,0.2,0.0,0.0,1.0,0.0
25%,2.0,0.0,0.0,22.0,7.6,0.0,1.0,0.0
50%,3.0,0.0,0.0,29.9,8.1,0.0,1.0,0.0
75%,3.0,1.0,0.0,35.0,15.0,1.0,3.0,1.0
max,3.0,8.0,9.0,80.0,128.1,10.0,11.0,1.0

In [70]:
df['embarked'].describe()

count            1309
unique              3
top       Southampton
freq              916
Name: embarked, dtype: object

In [71]:
df['pclass'].unique()

array([1, 2, 3])

In [72]:
df['pclass'].value_counts()

pclass
3    709
1    323
2    277
Name: count, dtype: int64

In [73]:
df.columns

Index(['pclass', 'Title', 'F_name', 'L_name', 'sibsp', 'parch', 'Gender',
       'Age', 'fare', 'ticket', 'Their_family_count', 'Number_of_Passager',
       'Companion_type', 'embarked', 'Age_group', 'Social_Status', 'survived'],
      dtype='object')

In [77]:
col=['pclass', 'Gender','embarked']
for c in col:
    print(df[c].value_counts(),end='\n\n\n')

pclass
3    709
1    323
2    277
Name: count, dtype: int64


Gender
Male      843
Female    466
Name: count, dtype: int64


embarked
Southampton    916
Cherbourge     270
Queenstown     123
Name: count, dtype: int64

In [ ]:
#extraction, clesning, feature engg, data manipulation, analyze data(matplotlib and seaborn)